<a href="https://colab.research.google.com/github/theakash07/python_codes/blob/google_collab/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

lst = [1, 2, 3]
a = np.array(lst, copy=True) #if copy is true that means it is copying the original content of the lst so if we changing the original lst it doesn't affect the array or if we change the array it doesn't affect the original list.
  #both the array and list is independent so changing in any one doesn't affect the array or lst..
lst[0]=9
print(lst)  # no change to array
print(a)

lst = [1, 2, 3]
a = np.array(lst, copy=False)
a[0] = 0
print(lst) #no change to original
print(a)

lst = [1, 2, 3]
a = np.array(lst)
a[0] = 0
print(lst) #no change to original
print(a)

[9, 2, 3]
[1 2 3]
[1, 2, 3]
[0 2 3]
[1, 2, 3]
[0 2 3]


**Below using dtype object to convert the particular element into best precision
like int the array there are only one elements and using dtype=np.float16 which is converting it to the half precision and using [0] to access the element which is at position 0.**

In [14]:
import numpy as np
#here we are using the dtype 16 bits which is 2 bytes so the precision will be about 4 digits.
a = np.array([1.3738729019013636723763, 1.23243328979877893], dtype=np.float16)[1]
print("float16:", a)
#here we are using the dtype 32 bytes which is 4 bytes so the precision will be about 8 digits.
a = np.array([1.3738729019013636723763], dtype=np.float32)[0]
print("float32:", a)
#here we are using the dtype 64 bytes which is 8 bytes so the precision will be about 16 digits.
a = np.array([1.3738729019013636723763], dtype=np.float64)[0]
print("float64:", a)
#here we are using the dtype 128 bytes which is 16 bytes so the precision will be about  32 digits.
# float128 is not available on all platforms
a = np.array([1.3738729019013636723763], dtype=np.float128)[0]
print("float128:", a)

float16: 1.232
float32: 1.3738729
float64: 1.3738729019013636
float128: 1.3738729019013635746


In [3]:
#a = np.array([0.0, 2.0, 3.0, 4.0, 5.0])
#print(a[0])
# 0.0
#a[0] = 1.0 #you can change single element in an array
#print(a)
# [1., 2., 3., 4., 5.]
#print(a)

0.0
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [9]:
#we can access multiple elements at a time
x=np.array([2,3,4,5,6])
print(x[[0,2,4]])
x[[0,2,4]]=[4,6,10]
print(x)

[2 4 6]
[ 4  3  6  5 10]


NEGATIVE INDEXING

In [10]:
d=np.array([1,23,4,5,3])
print(d[-1]) #in array we can do negative indexing as well

3


**Slicing of elements in array**
 the format is a[start: stop: step]. As an example, let’s get the first three elements of an array:

In [13]:
a=np.array([3,4,5,6,7])
print(a[0: 3])

print(a[0: -1]) #this is negative indexing

print(a[:: -1]) #we can reverse the elements of array using negative indexing elements.



[3 4 5]
[3 4 5 6]
[7 6 5 4 3]


**Append, insert, delete, and sort**

In [18]:
#To append means to add elements to the end. We can append single elements to a NumPy array just like we do with lists:
#append always happens at the End of the array
n=np.array([3,4,5,6])
n=np.append(n,8)
print(n)
#we can append multiple elements in the array as well
a = np.array([1.0, 2.0])
a = np.append(a, [4.0, 5.0])
print(a)
[1., 2., 4., 5.]

[3 4 5 6 8]
[1. 2. 4. 5.]


[1.0, 2.0, 4.0, 5.0]

In [23]:
#inserting list of elements at positions

a=np.array([3,4,5,6])
a=np.insert(a, 3, values=88)
print(a)



[ 3  4  5 88  6]


**Insert into NumPy array**

In [30]:
a=np.array([3,5,6,7,8])
a=np.insert(a,4, values=[53,45]) #here we are finding a postion and inserting multiple elements from there..
print(a)

# Insert multiple elements at multiple positions
a = np.insert(a, [3, 5], values=[4.5, 5.5])  #here you can insert multiple elements at a time to multiple position.
# a is nop [1. , 2. , 3. , 4.5, 4. , 5. , 5.5]


[ 3  5  6  7 53 45  8]


**Delete elements from NumPy array**

In [33]:
a=np.array([2,3,4,5,6])
a=np.delete(a,-1) #deleting only one element using negative indexing
print(a)

b=np.array([9,8,7,6,5,4])
b=np.delete(b,[2,3])
print(b)

[2 3 4 5]
[9 8 5 4]


Sorting NumPy array :
There are two ways to sort a NumPy array: in-place sort and creating a new, sorted array. To start with that last one:

In [34]:
a=np.array([9,3,10,5,11])
b=np.sort(a)
print(b)

[ 3  5  9 10 11]


In [35]:
#in-place sort, do as follows:
a = np.array([1.0, 3.0, 2.0, 4.0, 5.0])
a.sort()
# a is now [1., 2., 3., 4., 5.]
print(a)


[1. 2. 3. 4. 5.]
