<a href="https://colab.research.google.com/github/theakash07/python_codes/blob/google_collab/NumpyDay1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

lst = [1, 2, 3]
a = np.array(lst, copy=True) #if copy is true that means it is copying the original content of the lst so if we changing the original lst it doesn't affect the array or if we change the array it doesn't affect the original list.
a[0] = 0  #both the array and list is independent so changing in any one doesn't affect the array or lst..
lst[0]=9
print(lst)  # no change to array
print(a)

lst = [1, 2, 3]
a = np.array(lst, copy=False)
a[0] = 0
print(lst) #no change to original
print(a)

lst = [1, 2, 3]
a = np.array(lst)
a[0] = 0
print(lst) #no change to original
print(a)

[9, 2, 3]
[0 2 3]
[1, 2, 3]
[0 2 3]
[1, 2, 3]
[0 2 3]


**Below using dtype object to convert the particular element into best precision
like int the array there are only one elements and using dtype=np.float16 which is converting it to the half precision and using [0] to access the element which is at position 0.**

In [14]:
import numpy as np
#here we are using the dtype 16 bits which is 2 bytes so the precision will be about 4 digits.
a = np.array([1.3738729019013636723763, 1.23243328979877893], dtype=np.float16)[1]
print("float16:", a)
#here we are using the dtype 32 bytes which is 4 bytes so the precision will be about 8 digits.
a = np.array([1.3738729019013636723763], dtype=np.float32)[0]
print("float32:", a)
#here we are using the dtype 64 bytes which is 8 bytes so the precision will be about 16 digits.
a = np.array([1.3738729019013636723763], dtype=np.float64)[0]
print("float64:", a)
#here we are using the dtype 128 bytes which is 16 bytes so the precision will be about  32 digits.
# float128 is not available on all platforms
a = np.array([1.3738729019013636723763], dtype=np.float128)[0]
print("float128:", a)

float16: 1.232
float32: 1.3738729
float64: 1.3738729019013636
float128: 1.3738729019013635746
